### ISSUE TITLE
Hosting on github pages?

### ISSUE THREAD

**Issue by gdevenyi** [tlnagy/jekyll-lab-notebook#3]
I'm pretty inexperienced with ruby/gems, so I can't really tell.

Can this system be hosted on github pages instead of local serving?

**Comment by tlnagy** [comment]
I believe so, but it wouldn't be that straight forward since Github doesn't allow any custom plugins to be used with the Github Pages version of Jekyll. I think that you could be able to set up something that uses Travis CI to build the website and then deploy the final version to Github Pages. Sorry it isn't easier.

**Comment by gdevenyi** [comment]
Hrm thanks.

This looks awesome but I'm looking for something a little more plug and play for my less tech-savvy users.
